# Define version
version: 1

# Define your URLs (Mandatory!)
# URLs should start with - (remove the comment symbol #)
# Replace the values with your tokens/ids
# For example a telegram URL would look like:
# - tgram://123456789:AABx8iXjE5C-vG4SDhf6ARgdFgxYxhuHb4A/-606743502
#https://discord.com/api/webhooks/880116169208643666/neZq7DV0Ew9ukmF7fZR8ffqUxs5NHobzuvmiUyFhcmuaewSlVRT1c3qOLvICvT7XYfWA
urls:
  # - tgram://TOKEN/CHAT_ID
   - discord://KnightKim/880116169208643666/neZq7DV0Ew9ukmF7fZR8ffqUxs5NHobzuvmiUyFhcmuaewSlVRT1c3qOLvICvT7XYfWA/
  # - slack://tokenA/tokenB/tokenC
  # More options here: https://github.com/caronc/apprise
